

INSERT INTO quizmaker_categories( cat_name, cat_description,  cat_theme) VALUES ('Test', 'Catégorie de test', 'default');

INSERT INTO quizmaker_messages( msg_code, msg_constant) VALUES 
('message01', 'MESSAGE01'),
('results', 'RESULTS'),
('comboboxSortList', 'COMBOBOXSORTLIST'),
('radio', 'RADIO'),
('checkboxSimple', 'CHECKBOXSIMPLE'),
('textbox', 'TEXTBOX'),
('textboxMultiple', 'TEXTBOXMULTIPLE'),
('allType', 'ALLTYPE'),
('forPoints', 'FORPOINTS'),
('forChrono', 'FORCHRONO'),
('forPointsTimer', 'FORPOINTSTIMER'),
('resultOnSlide', 'RESULTONSLIDE'),
('btnNext', 'BTNNEXT'),
('btnPrevious', 'BTNPREVIOUS'),
('btnSubmit', 'BTNSUBMIT'),
('btnContinue', 'BTNCONTINUE'),
('btnReload', 'BTNRELOAD'),
('btnAntiseche', 'BTNANTISECHE'),
('showReponses', 'SHOWREPONSES'),
('btnReloadList', 'BTNRELOADLIST'),
('btnReloadText', 'BTNRELOADTEXT'),
('resultBravo0 ', 'RESULTBRAVO0'),
('resultBravo1 ', 'RESULTBRAVO1'),
('resultBravo2 ', 'RESULTBRAVO2'),
('resultBravo3 ', 'RESULTBRAVO3'),
('resultScore ', 'RESULTSCORE'),
('points ', 'POINTS'),
('bonneReponse ', 'BONNEREPONSE'),
('tplWord ', 'TPLWORD'),
('tplWord2 ', 'TPLWORD2'),
('tplReponseTable ', 'TPLREPONSETABLE'),
('tplReponseDblTable ', 'TPLREPONSEDBLTABLE'),
('tplReponseDblTD ', 'TPLREPONSEDBLTD'),
('tplReponseTD ', 'TPLREPONSETD');
