

INSERT INTO quizmaker_categories( cat_name, cat_description,  cat_theme) VALUES ('Test', 'Catégorie de test', 'default');

INSERT INTO quizmaker_messages( msg_code, msg_constant) VALUES 
('message01', 'MESSAGES_JS_MESSAGE01'),
('results', 'MESSAGES_JS_RESULTS'),
('sortCombobox', 'MESSAGES_JS_SORTCOMBOBOX'),
('radio', 'MESSAGES_JS_RADIO'),
('checkbox', 'MESSAGES_JS_CHECKBOX'),
('textbox', 'MESSAGES_JS_TEXTBOX'),
('multiTextbox', 'MESSAGES_JS_MULTITEXTBOX'),
('allType', 'MESSAGES_JS_ALLTYPE'),
('forPoints', 'MESSAGES_JS_FORPOINTS'),
('forChrono', 'MESSAGES_JS_FORCHRONO'),
('forPointsTimer', 'MESSAGES_JS_FORPOINTSTIMER'),
('resultOnSlide', 'MESSAGES_JS_RESULTONSLIDE'),
('btnNext', 'MESSAGES_JS_BTNNEXT'),
('btnPrevious', 'MESSAGES_JS_BTNPREVIOUS'),
('btnSubmit', 'MESSAGES_JS_BTNSUBMIT'),
('btnContinue', 'MESSAGES_JS_BTNCONTINUE'),
('btnReload', 'MESSAGES_JS_BTNRELOAD'),
('btnAntiseche', 'MESSAGES_JS_BTNANTISECHE'),
('showReponses', 'MESSAGES_JS_SHOWREPONSES'),
('btnReloadList', 'MESSAGES_JS_BTNRELOADLIST'),
('btnReloadText', 'MESSAGES_JS_BTNRELOADTEXT'),
('resultBravo0 ', 'MESSAGES_JS_RESULTBRAVO0 '),
('resultBravo1 ', 'MESSAGES_JS_RESULTBRAVO1 '),
('resultBravo2 ', 'MESSAGES_JS_RESULTBRAVO2 '),
('resultBravo3 ', 'MESSAGES_JS_RESULTBRAVO3 '),
('resultScore ', 'MESSAGES_JS_RESULTSCORE '),
('points ', 'MESSAGES_JS_POINTS '),
('bonneReponse ', 'MESSAGES_JS_BONNEREPONSE '),
('tplWord ', 'MESSAGES_JS_TPLWORD '),
('tplWord2 ', 'MESSAGES_JS_TPLWORD2 '),
('tplReponseTable ', 'MESSAGES_JS_TPLREPONSETABLE '),
('tplReponseDblTable ', 'MESSAGES_JS_TPLREPONSEDBLTABLE '),
('tplReponseDblTD ', 'MESSAGES_JS_TPLREPONSEDBLTD '),
('tplReponseTD ', 'MESSAGES_JS_TPLREPONSETD ');
